version: "3"

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
    php:
        image: php:7.4-fpm-alpine
    mysql:
        image: mysql:5.7
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: vabsplugin
            MYSQL_USER: uhorn
            MYSQL_PASSWORD: password

    wordpress:
        depends_on:
            - nginx
            - php
            - mysql
        image: wordpress:latest
        ports:
            - "8088:80"
        volumes:
            - ./wp-content:/var/www/html/wp-content
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: uhorn
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: vabsplugin
            WORDPRESS_DEBUG: 1
volumes:
    mysql: {}
